### ISSUE TITLE
failure of Blade-Shape deleting

### ISSUE THREAD

**Issue by xix695** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#106]
when the user tried to delete an existing Blade-Shape, but the item appeared again after the user created another Blade-Shape here.
The tester uses an item "as" to test the functionality.
Do we need to fix the bug?

Please see the short video below to get context.
https://usask.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=1974df60-032b-4c50-bd1c-b13500f35ecd

**Comment by m-jewel** [comment]
Could you try:
- stop docker (docker-compose down)
- delete your (postgresql) database folder as seen in the screenshot below
- run docker again (docker-compose up)
<img width="196" alt="Screenshot 2024-03-16 at 9 04 03 AM" src="https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/assets/145354608/d56e500e-d574-461c-8f26-e6223af4a89f">

This is because I've tried to reproduce the error you said but it does not occur on my end (see video below).
https://usask.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=9a4dbcc0-b8ba-49ad-8798-b13500fa05ad

**Comment by xix695** [comment]
Could you authorize me to access your video?

**Comment by m-jewel** [comment]
done

**Comment by xix695** [comment]
After did what you told me, the error occurred once on my computer but I again deleted the database,
then docker compose up, this time the error did not occur again. So I think we can close the issue for now.
