### ISSUE TITLE
Story 2

### ISSUE THREAD

**Issue by Uv2002** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#58]
Story 2 is saying that I can add new points into under the site. there should be catalouge page availble so that I can develop that feature. story 2 can be spilt into two user story. one is catalouge with site name and another one is  when I use any site to go on the projectile points , that can be another user story.

**Comment by nisarg-11-here** [comment]
Let me explain how the system should work. There should be a “create new Artifact” button on the top right of the catalog page, now the same button should be there on each page (when inside a specific site). There should be sites created and displayed when you add values to site using the pre-populated data management page (feature 6) based on the sites inside the sites table. Now They should be empty if there is no artifact (projectile point) in the database belonging to that site. 
now when user creates a new point, they will have to select the site each time. So that site page should be created automatically when there are sites in the sites table. Hope I was clear.
